In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

print "Libs imported"

Libs imported


In [2]:
# Setting up some data

mock_data = np.random.randn(5,5)

print mock_data

[[-0.51462537  0.03370944 -0.36366092 -0.2987136  -1.09276111]
 [-0.12052034  0.27924259 -0.83597403  0.37515617  1.03717136]
 [-0.60636573  0.68700735 -0.35622464  0.5795953   0.56494885]
 [ 0.03511696 -1.16032278  0.21716032  1.1102065  -0.51695795]
 [-0.78260783  0.90418282  1.60662806 -0.64830641 -0.54101053]]


In [3]:
# Set up the plotting of the data

plt.figure()

sns.heatmap(mock_data)

plt.show()